config/routes.rb
Reviews::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :snippets
  resources :reviews, :only => [:new, :create, :destroy]

  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete

  root :to => 'home#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :snippets

  validates :name, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :contents, :line
  belongs_to :user
  belongs_to :snippet

  validates :user_id, :presence => true
  validates :contents, :presence => true
  validates :user_id, :presence => true
  validates :snippet_id, :presence => true

  default_scope :order => 'reviews.created_at DESC'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :code, :title, :language_id, :description
  belongs_to :user
  belongs_to :language
  has_many :reviews, :dependent => :destroy

  validates :user_id, :presence => true
  validates :code, :presence => true
  validates :title, :presence => true
  validates :language_id, :presence => true

  default_scope :order => 'snippets.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :snippets, :dependent => :destroy
  has_many :reviews, :dependent => :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, :if => :password_validation_required?
  validates :password_confirmation, :presence => true,
     :if => :password_validation_required?

  private

  def password_validation_required?
    password_digest.blank? || !@password.blank?
  end
  
  def create_remember_token
    self.remember_token = SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :logged_in_user

  def new
    @review = Review.new
  end

  def create
    snippet_id = params[:review][:snippet_id]
    params[:review].delete :snippet_id
    @review = current_user.reviews.build(params[:review])
    @review.snippet_id = snippet_id
    if @review.save
      render :json => { "success" => true, "redirect" => root_path }
    else
      render 'new'
    end
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login user
      render :json => { "success" => true, "redirect" => root_path }
    else
      flash.now[:badlogin] = true
      render 'new'
    end
  end

  def destroy
    logout
    render :json => { "success" => true, "redirect" => root_path }
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  before_filter :logged_in_user

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = current_user.snippets.build(params[:snippet])
    if @snippet.save
      redirect_to snippet_path(@snippet.id)
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    @snippet = Snippet.find_by_id(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :resolve_layout
  before_filter :logged_in_user, :only => [:show]
  before_filter :correct_user, :only => [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login @user
      render :json => { "success" => true, "redirect" => root_path }
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @is_me = (@user.id == current_user.id)
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update_attributes params[:user]
      login @user
      render :json => { "success" => true }
    else
      render :json => { "success" => false }
    end
  end

  private

  def resolve_layout
    if action_name == 'show'
      'application'
    else
      'users'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    @current_user == user
  end

  def loggedin?
    !self.current_user.nil?
  end

  def logout
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def logged_in_user
    unless loggedin?
      redirect_to root_path
    end
  end

  def correct_user
    @user = User.find_by_id(params[:id])
    unless loggedin? && current_user?(@user)
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_home.html.erb
<div class="row">
  <center>
  <div class="span4">
    <h3>Hello, <%= current_user.name %>!</h3>

    <p>
      Click a button to get started.
    </p>
  </div>

  <div class="span4">
    <p>
      <%= link_to "Get your code reviewed", new_snippet_path, :class =>
        "btn btn-primary btn-large" %>
    </p>
  </div>

  <div class="span4">
    <p>
      <a class="btn btn-primary btn-large" href="#">
        Review someone else's code
      </a>
    </p>
  </div>
</center>
</div>

<div class="row">
  <div class="span12 spacer"></div>
</div>

<hr />

<%= render "shared/user_content" %>

app/views/home/_splash.html.erb
<div class="hero-unit">
  <h1>Get your code reviewed...</h1>
  <h4>by other people!</h4>

  <p>
    <a class="btn" href="#signup" data-toggle="modal">Sign up</a> 
    <a class="btn" href="#login" data-toggle="modal">Log in</a>
  </p>

</div>
</div>

<div class="modal fade" id="signup">
</div>

<div class="modal fade" id="login">
</div>

<input type="hidden" name="signup_url" id="signup_url" value="<%= new_user_path %>" />

<input type="hidden" name="login_url" id="login_url" value="<%= new_session_path %>" />

app/views/home/index.html.erb
<div class="container">

<% if loggedin? %>
<%= render "home" %>
<% else %>
<%= render "splash" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Code Reviews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Code Reviews", root_path, :class => "brand" %>
      <% if loggedin? %>
      <%= render "/shared/home_nav" %>
      <% else %>
      <%= render "/shared/splash_nav" %>
      <% end %>
    </div>
  </div>
</div>


<%= yield %>

</body>
</html>

app/views/layouts/reviews.html.erb
<%= yield %>

app/views/layouts/sessions.html.erb
<%= yield %>

app/views/layouts/users.html.erb
<%= yield %>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>

<%= f.hidden_field :snippet_id %>

<fieldset class="control-group
                 <% if @review.errors[:contents].any? %>error<% end %>">
  <div class="controls">
    <%= text_area :review, :contents, :class => "span4", :rows => 10%>
  </div>
</fieldset>

<%= f.submit "Review", :class => "btn btn-large btn-primary" %>

<% end %>

app/views/shared/_home_nav.html.erb
<ul class="nav pull-right">
<li> <%= link_to current_user.name, current_user %> </li>
<li> <%= link_to "Logout", logout_path, :id => "logout" %></li>
</ul>

app/views/shared/_login_header.html.erb
<div class="modal-header">
  <h2>Log in</h2>
</div>

app/views/shared/_signup_header.html.erb
<div class="modal-header">
  <h2>Sign up now</h2>
</div>

app/views/shared/_user_content.html.erb
<% if !@user
     @user = current_user
   end %>

<div class="row">
  <center>

    <div class="span4 offset2">
      <h3>
        <% if @user.id == current_user.id %>
        Your 
        <% else %>
        <%= @user.name %>'s 
        <% end %>
        code
      </h3>

      <% if @user.snippets.empty? %>
      <br />
      <p>None yet!</p>
      <% end %>

      <dl class="dl-horizontal">
        <% for c in @user.snippets %>
        <dt><%= link_to c.title, c %></dt>
        <dd><%= c.description %></dd>
        <% end %>
      </dl>
    </div>

    <div class="span4">
      <h3>
        <% if @user.id == current_user.id %>
        Your 
        <% else %>
        <%= @user.name %>'s 
        <% end %>
        reviews
      </h3>

      <% if @user.reviews.empty? %>
      <br />
      <p>None yet!</p>
      <% end %>
      
      <dl class="dl-horizontal">
        <% for r in @user.reviews %>
        <dt>On <%= link_to r.snippet.title, r.snippet %></dt>
        <dd><%= r.contents %></dd>
        <% end %>
      </dl>

    </div>

  </center>
</div>

app/views/snippets/new.html.erb
<div class="container">

  <h1>Upload Code</h1>

  <%= form_for @snippet do |f| %>

  <fieldset class="control-group 
                   <% if @snippet.errors[:title].any? %>error<% end %>">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
      <% if @snippet.errors[:title].any? %>
      <span class="help-inline">Title <%= @snippet.errors[:title] %>.</span>
      <% end %>
    </div>
  </fieldset>

  <fieldset class="control-group 
            <% if @snippet.errors[:language_id].any? %>error<% end %>">

    <%= f.label :language_id, :class => "control-label" %>
    <div class="controls">
      <%= collection_select :snippet, :language_id, Language.all, :id, :name %>
      <% if @snippet.errors[:language_id].any? %>
      <span class="help-inline">Language <%= @snippet.errors[:language_id] %>.</span>
      <% end %>
    </div>

  </fieldset>

  <fieldset class="control-group
            <% if @snippet.errors[:description].any? %>error<% end %>">

    <%= f.label :description, :class => "control-label" %>

    <div class="controls">

      <%= text_area :snippet, :description, :class =>
            "span6", :rows => 5 %>

      <% if @snippet.errors[:description].any? %>
      <span class="help-inline">
        Description <%= @snippet.errors[:description] %>.
      </span>
      <% end %>

    </div>
  </fieldset>

  <fieldset class="control-group
            <% if @snippet.errors[:code].any? %>error<% end %>">

    <%= f.label :code, :class => "control-label" %>

    <div class="controls">

      <%= text_area :snippet, :code, :class => "span8", :rows => 10 %>

      <% if @snippet.errors[:code].any? %>
      <span class="help-inline">Code <%= @snippet.errors[:code] %>.</span>
      <% end %>

    </div>
  </fieldset>

  <%= f.submit "Upload", :class => "btn btn-primary btn-large" %>

  <% end %>

</div>

app/views/snippets/show.html.erb
<div class="container">

  <div class="spacer span12"></div>

  <div class="row">
    <div class="span7">
      <h2><%= @snippet.title %></h2>
      <h4>Author: <%= @snippet.user.name %></h4>
      <h4>Date: <%= @snippet.created_at.to_s :long %></h4>
      <h4>Language: <%= @snippet.language.name %></h4>


      <% if @snippet.description %>
      <p><%= @snippet.description %></p>
      <% end %>

      <div class="spacer"></div>
      <pre class="prettyprint linenums"><%= @snippet.code %></pre>
    </div>

    <input type="hidden" id="snippet_id" value="<%= @snippet.id %>" />

    <% if @snippet.user.name != current_user.name %>
    <div class="span5" id="new_review">
      <%= link_to "", new_review_path, :id => "new_review_url", :class =>
            "hidden" %>
    </div>
    <% end %>
  </div>

  <hr />

  <% if !@snippet.reviews.empty? %>
  <div class="row">    
    <div class="span12">
      <% for r in @snippet.reviews %>
      <p>
        <%= r.contents %><br />
        <small><i>by <%= link_to r.user.name, r.user %></i> at <%= r.created_at.to_s :long %></small>
      </p>
      </hr>

      <% end %>
    </div>
  </div>
  <% end %>
  
</div>

app/views/users/new.html.erb
<%= render "shared/signup_header" %>

<div class="modal-body">

  <%= form_for @user, :html => 
        { "data-result-container" => "#signup" } do |f| %>

 <fieldset class="control-group error hidden" id="ajax_err">
    <h4>
      <span class="help-inline">
        Sorry, your registration could not be completed.
      </span>
    </h4>
  </fieldset>

  <fieldset class="control-group 
                   <% if @user.errors[:email].any? %>error<% end %>">
    <%= f.label :email, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
      <% if @user.errors[:email].any? %>
      <span class="help-inline">Email <%= @user.errors[:email] %>.</span>
      <% end %>
    </div>
  </fieldset>
  
  <fieldset class="control-group
                   <% if @user.errors[:name].any? %>error<% end %>">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
      <% if @user.errors[:name].any? %>
      <span class="help-inline">Name <%= @user.errors[:name] %>.</span>
      <% end %>
    </div>

  </fieldset>

  <fieldset class="control-group
                   <% if @user.errors[:password].any? %>error<% end %>">
    <%= f.label :password, :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password %>
      <% if @user.errors[:password].any? %>
      <span class="help-inline">Password <%= @user.errors[:password] %>.</span>
      <% end %>
    </div>

  </fieldset>  

  <fieldset class="control-group
                   <% if @user.errors[:password_confirmation].any? %>
                   error
                   <% end %>">
    <%= f.label :password_confirmation, :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
      <% if @user.errors[:password_confirmation].any? %>
      <span class="help-inline">Password confirmation 
        <%= @user.errors[:password_confirmation] %>.</span>
      <% end %>
    </div>

  </fieldset>  

  <%= f.submit "Sign up", :class => "btn btn-primary btn-large" %>

  <% end %>
</div>

app/views/users/registered.html.erb
<%= render "shared/signup_header" %>

<div class="modal-body">
  <h4>Success!</h4>
</div>

app/views/users/show.html.erb
<div class="user_form">

  <%= form_for @user, :method => "put" do |f| %>

  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>
          <span class="editable" id="show-name" data-info="name">
            <span class="data"><%= @user.name %></span> 
            <% if @is_me %><%= link_to "", "#", :class => "icon-pencil edit" %><% end %>
          </span>
        </h1>

        <fieldset id="edit-name" class="control-group edit
                                        <% if @user.errors[:name].any? %>error<% end %>">
          <div class="controls">
            <%= f.text_field :name %>
          </div>
        </fieldset>

        <p>
          Member since <%= @user.created_at.to_s :long %>.
        </p>
      </div>
    </div>

    <hr />

    <%= render "shared/user_content" %>

  </div>

  <%= f.submit "Submit", :class => "hidden" %>

  <% end %>

</div>